import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// Config do Shadcn
import { cn } from '@/lib/utils'
import { Sidebar } from "@/components/sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* Configurando o Shadcn com ClassName */}
      <body className={cn("min-h-sscreen bg-background font-sans antialised",
        inter.className
      )}>
        {/* Passando os componentes que serao renderizados em todas as páginas */}
        <Sidebar/>
        {children}
        </body>
    </html>
  );
}
